[options]
addons_path = /mnt/extra-addons/training-tech-enabel/custom_addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$Zax1DiFEKGXMGYOQ0vq/tw$ySR.KzZ5jBkxk.F.XgNqEPp70a9GC5QBmXuHuVTbyyBKfDxam6O3JUpSTPlRfZ9P1g9YZN0MM222cFhHf34PqA

